// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace susak.Models;

public partial class Clan
{
    public int ClanId { get; set; }

    public string Ime { get; set; }

    public string Prezime { get; set; }

    public string Oib { get; set; }

    public DateTime? DatumRodjenja { get; set; }

    public string Adresa { get; set; }

    public string Kontakt { get; set; }

    public virtual ICollection<Clanarina> Clanarina { get; set; } = new List<Clanarina>();

    public virtual ICollection<Prisustvo> Prisustvo { get; set; } = new List<Prisustvo>();

    public virtual ICollection<Sudjelovanje> Sudjelovanje { get; set; } = new List<Sudjelovanje>();

    public virtual ICollection<Disciplina> Disciplina { get; set; } = new List<Disciplina>();
}