// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace susak.Models;

public partial class Clanarina
{
    public int ClanarinaId { get; set; }

    public int? ClanId { get; set; }

    public decimal? Iznos { get; set; }

    public DateTime? DatumUplate { get; set; }

    public string Status { get; set; }

    public virtual Clan Clan { get; set; }
}