// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace susak.Models;

public partial class Disciplina
{
    public int DisciplinaId { get; set; }

    public string Naziv { get; set; }

    public string Opis { get; set; }

    public virtual ICollection<Trening> Trening { get; set; } = new List<Trening>();

    public virtual ICollection<Clan> Clan { get; set; } = new List<Clan>();

    public virtual ICollection<Trener> Trener { get; set; } = new List<Trener>();
}