// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace susak.Models;

public partial class Korisnik
{
    public int KorisnikId { get; set; }

    public string KorisnickoIme { get; set; }

    public string Lozinka { get; set; }

    public int? UlogaId { get; set; }

    public virtual ICollection<Trener> Trener { get; set; } = new List<Trener>();

    public virtual Uloga Uloga { get; set; }
}