// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace susak.Models;

public partial class Natjecanje
{
    public int NatjecanjeId { get; set; }

    public string Naziv { get; set; }

    public DateTime? Datum { get; set; }

    public string Lokacija { get; set; }

    public virtual ICollection<Sudjelovanje> Sudjelovanje { get; set; } = new List<Sudjelovanje>();
}