// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace susak.Models;

public partial class Prisustvo
{
    public int TreningId { get; set; }

    public int ClanId { get; set; }

    public string Status { get; set; }

    public virtual Clan Clan { get; set; }

    public virtual Trening Trening { get; set; }
}