// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace susak.Models;

public partial class Sudjelovanje
{
    public int SudjelovanjeId { get; set; }

    public int? ClanId { get; set; }

    public int? NatjecanjeId { get; set; }

    public string Rezultat { get; set; }

    public virtual Clan Clan { get; set; }

    public virtual Natjecanje Natjecanje { get; set; }
}