// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace susak.Models;

public partial class susakContext : DbContext
{
    public susakContext(DbContextOptions<susakContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Clan> Clan { get; set; }

    public virtual DbSet<Clanarina> Clanarina { get; set; }

    public virtual DbSet<Disciplina> Disciplina { get; set; }

    public virtual DbSet<Korisnik> Korisnik { get; set; }

    public virtual DbSet<Natjecanje> Natjecanje { get; set; }

    public virtual DbSet<Prisustvo> Prisustvo { get; set; }

    public virtual DbSet<Sudjelovanje> Sudjelovanje { get; set; }

    public virtual DbSet<Trener> Trener { get; set; }

    public virtual DbSet<Trening> Trening { get; set; }

    public virtual DbSet<Uloga> Uloga { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Clan>(entity =>
        {
            entity.HasKey(e => e.ClanId).HasName("PK__Clan__EC03AA4449511F7C");

            entity.Property(e => e.ClanId).HasColumnName("ClanID");
            entity.Property(e => e.Adresa).HasMaxLength(100);
            entity.Property(e => e.DatumRodjenja).HasColumnType("date");
            entity.Property(e => e.Ime).HasMaxLength(50);
            entity.Property(e => e.Kontakt).HasMaxLength(50);
            entity.Property(e => e.Oib)
                .HasMaxLength(11)
                .IsUnicode(false)
                .HasColumnName("OIB");
            entity.Property(e => e.Prezime).HasMaxLength(50);

            entity.HasMany(d => d.Disciplina).WithMany(p => p.Clan)
                .UsingEntity<Dictionary<string, object>>(
                    "ClanDisciplina",
                    r => r.HasOne<Disciplina>().WithMany()
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__ClanDisci__Disci__534D60F1"),
                    l => l.HasOne<Clan>().WithMany()
                        .HasForeignKey("ClanId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__ClanDisci__ClanI__52593CB8"),
                    j =>
                    {
                        j.HasKey("ClanId", "DisciplinaId").HasName("PK__ClanDisc__1E83BF3584F08F8C");
                        j.IndexerProperty<int>("ClanId").HasColumnName("ClanID");
                        j.IndexerProperty<int>("DisciplinaId").HasColumnName("DisciplinaID");
                    });
        });

        modelBuilder.Entity<Clanarina>(entity =>
        {
            entity.HasKey(e => e.ClanarinaId).HasName("PK__Clanarin__C51E3BB744E8713A");

            entity.Property(e => e.ClanarinaId).HasColumnName("ClanarinaID");
            entity.Property(e => e.ClanId).HasColumnName("ClanID");
            entity.Property(e => e.DatumUplate).HasColumnType("date");
            entity.Property(e => e.Iznos).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Status).HasMaxLength(50);

            entity.HasOne(d => d.Clan).WithMany(p => p.Clanarina)
                .HasForeignKey(d => d.ClanId)
                .HasConstraintName("FK__Clanarina__ClanI__48CFD27E");
        });

        modelBuilder.Entity<Disciplina>(entity =>
        {
            entity.HasKey(e => e.DisciplinaId).HasName("PK__Discipli__2801571EB64562B9");

            entity.Property(e => e.DisciplinaId).HasColumnName("DisciplinaID");
            entity.Property(e => e.Naziv).HasMaxLength(100);
            entity.Property(e => e.Opis).HasColumnType("text");
        });

        modelBuilder.Entity<Korisnik>(entity =>
        {
            entity.HasKey(e => e.KorisnikId).HasName("PK__Korisnik__80B06D61F00B072B");

            entity.Property(e => e.KorisnikId).HasColumnName("KorisnikID");
            entity.Property(e => e.KorisnickoIme)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Lozinka)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.UlogaId).HasColumnName("UlogaID");

            entity.HasOne(d => d.Uloga).WithMany(p => p.Korisnik)
                .HasForeignKey(d => d.UlogaId)
                .HasConstraintName("FK__Korisnik__UlogaI__398D8EEE");
        });

        modelBuilder.Entity<Natjecanje>(entity =>
        {
            entity.HasKey(e => e.NatjecanjeId).HasName("PK__Natjecan__2345D27C8DF82D52");

            entity.Property(e => e.NatjecanjeId).HasColumnName("NatjecanjeID");
            entity.Property(e => e.Datum).HasColumnType("date");
            entity.Property(e => e.Lokacija).HasMaxLength(100);
            entity.Property(e => e.Naziv).HasMaxLength(100);
        });

        modelBuilder.Entity<Prisustvo>(entity =>
        {
            entity.HasKey(e => new { e.TreningId, e.ClanId }).HasName("PK__Prisustv__65C4925766019714");

            entity.Property(e => e.TreningId).HasColumnName("TreningID");
            entity.Property(e => e.ClanId).HasColumnName("ClanID");
            entity.Property(e => e.Status).HasMaxLength(20);

            entity.HasOne(d => d.Clan).WithMany(p => p.Prisustvo)
                .HasForeignKey(d => d.ClanId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Prisustvo__ClanI__4F7CD00D");

            entity.HasOne(d => d.Trening).WithMany(p => p.Prisustvo)
                .HasForeignKey(d => d.TreningId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Prisustvo__Treni__4E88ABD4");
        });

        modelBuilder.Entity<Sudjelovanje>(entity =>
        {
            entity.HasKey(e => e.SudjelovanjeId).HasName("PK__Sudjelov__EBA615873E580BCC");

            entity.Property(e => e.SudjelovanjeId).HasColumnName("SudjelovanjeID");
            entity.Property(e => e.ClanId).HasColumnName("ClanID");
            entity.Property(e => e.NatjecanjeId).HasColumnName("NatjecanjeID");
            entity.Property(e => e.Rezultat).HasMaxLength(100);

            entity.HasOne(d => d.Clan).WithMany(p => p.Sudjelovanje)
                .HasForeignKey(d => d.ClanId)
                .HasConstraintName("FK__Sudjelova__ClanI__44FF419A");

            entity.HasOne(d => d.Natjecanje).WithMany(p => p.Sudjelovanje)
                .HasForeignKey(d => d.NatjecanjeId)
                .HasConstraintName("FK__Sudjelova__Natje__45F365D3");
        });

        modelBuilder.Entity<Trener>(entity =>
        {
            entity.HasKey(e => e.TrenerId).HasName("PK__Trener__ABE1A132B3E7F61E");

            entity.Property(e => e.TrenerId).HasColumnName("TrenerID");
            entity.Property(e => e.Ime).HasMaxLength(50);
            entity.Property(e => e.KorisnikId).HasColumnName("KorisnikID");
            entity.Property(e => e.Prezime).HasMaxLength(50);
            entity.Property(e => e.StrucnaSprema).HasMaxLength(100);

            entity.HasOne(d => d.Korisnik).WithMany(p => p.Trener)
                .HasForeignKey(d => d.KorisnikId)
                .HasConstraintName("FK__Trener__Korisnik__3E52440B");

            entity.HasMany(d => d.Disciplina).WithMany(p => p.Trener)
                .UsingEntity<Dictionary<string, object>>(
                    "TrenerDisciplina",
                    r => r.HasOne<Disciplina>().WithMany()
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__TrenerDis__Disci__571DF1D5"),
                    l => l.HasOne<Trener>().WithMany()
                        .HasForeignKey("TrenerId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__TrenerDis__Trene__5629CD9C"),
                    j =>
                    {
                        j.HasKey("TrenerId", "DisciplinaId").HasName("PK__TrenerDi__5961B443AC51B7EC");
                        j.IndexerProperty<int>("TrenerId").HasColumnName("TrenerID");
                        j.IndexerProperty<int>("DisciplinaId").HasColumnName("DisciplinaID");
                    });
        });

        modelBuilder.Entity<Trening>(entity =>
        {
            entity.HasKey(e => e.TreningId).HasName("PK__Trening__3B04A8F3B5EA08D6");

            entity.Property(e => e.TreningId).HasColumnName("TreningID");
            entity.Property(e => e.Datum).HasColumnType("date");
            entity.Property(e => e.DisciplinaId).HasColumnName("DisciplinaID");
            entity.Property(e => e.Opis).HasColumnType("text");

            entity.HasOne(d => d.Disciplina).WithMany(p => p.Trening)
                .HasForeignKey(d => d.DisciplinaId)
                .HasConstraintName("FK__Trening__Discipl__4BAC3F29");
        });

        modelBuilder.Entity<Uloga>(entity =>
        {
            entity.HasKey(e => e.UlogaId).HasName("PK__Uloga__DCAB23EBCE3F1233");

            entity.Property(e => e.UlogaId).HasColumnName("UlogaID");
            entity.Property(e => e.Naziv).HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}