// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace susak.Models;

public partial class Trener
{
    public int TrenerId { get; set; }

    public string Ime { get; set; }

    public string Prezime { get; set; }

    public string StrucnaSprema { get; set; }

    public int? KorisnikId { get; set; }

    public virtual Korisnik Korisnik { get; set; }

    public virtual ICollection<Disciplina> Disciplina { get; set; } = new List<Disciplina>();
}