// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace susak.Models;

public partial class Trening
{
    public int TreningId { get; set; }

    public int? DisciplinaId { get; set; }

    public DateTime? Datum { get; set; }

    public int? Trajanje { get; set; }

    public string Opis { get; set; }

    public virtual Disciplina Disciplina { get; set; }

    public virtual ICollection<Prisustvo> Prisustvo { get; set; } = new List<Prisustvo>();
}