// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace susak.Models;

public partial class Uloga
{
    public int UlogaId { get; set; }

    public string Naziv { get; set; }

    public virtual ICollection<Korisnik> Korisnik { get; set; } = new List<Korisnik>();
}